### ISSUE TITLE
add nav block at the end of blog pages

### ISSUE THREAD

**Issue by FaberVitale** [Roma-JS/roma-js-on-astro#14]
### Describe the problem

When reaching the end of long pages it would cool to have a nav block instead of having to scroll back up.

### Describe the proposed solution

Add nav block section at the end of the end of the following layouts:

- blogPostList
- blogPost
- CategoriesList

Nav block links:

- home
- blog index
- scroll to top

### Alternatives considered

We could alternatively just add a scroll to top button and call it a day.

### Importance

nice to have

**Comment by franciszek-szeptycki** [comment]
Hi, I would like to solve this issue, could you assign me to it?
