### ISSUE TITLE
add headless about pages endpoints 

### ISSUE THREAD

**Issue by FaberVitale** [Roma-JS/roma-js-on-astro#15]
### Describe the problem

I want to access to the content of the about pages without having to scrape the page.

### Describe the proposed solution

Add the following api endpoints:

- /api/about/it.json
- /api/about/en.json

We want the output json to have shape  [PostInfoDto](https://github.com/Roma-JS/roma-js-on-astro/blob/90ca987ea8b8d7a055806661d715d587d844fb66/src/pages/api/blog/post.json.ts#L3).

### Alternatives considered

None

### Importance

nice to have

**Comment by DavidePassafaro** [comment]
@FaberVitale please assign it to me
