### ISSUE TITLE
Missing date on featured next event (home page)

### ISSUE THREAD

**Issue by lifeisfoo** [Roma-JS/roma-js-on-astro#58]
### Describe the bug

Users can't know when the next event will be without opening the meetup link.
![image](https://github.com/Roma-JS/roma-js-on-astro/assets/3725610/82136327-61a9-4810-9f59-df920b571324)

The must be visibile inside the next event block.
![image](https://github.com/Roma-JS/roma-js-on-astro/assets/3725610/9466bf6b-c675-47ab-98cd-306bbadba445)

### System Info

```bash
any
```

### Severity

annoyance

**Comment by Samaresh-Das** [comment]
WOULD LIKE TO WORK ON THIS
