### ISSUE TITLE
[Seo] Fix incorrect brand name

### ISSUE THREAD

**Issue by FaberVitale** [Roma-JS/roma-js-on-astro#84]
### Describe the bug

Google incorrectly displays our website name as `roma.js` it should be `RomaJs` instead.

<img width="674" alt="Screenshot 2024-09-30 at 21 04 51" src="https://github.com/user-attachments/assets/cdba9154-c155-41c3-ae1e-e398b8ce3c45">

### System Info

```bash
not relevant
```

### Severity

annoyance

**Comment by FaberVitale** [comment]
### Bing

<img width="778" alt="Screenshot 2024-09-30 at 21 06 17" src="https://github.com/user-attachments/assets/4181fb2c-a672-45ad-a88c-782aa323357c">

**Comment by giorgiogalassi** [comment]
Hi,

For the main issue i've found [this](https://youtu.be/DPJ0AzJSlFE?feature=shared&t=51) that my help.

Looking at the pictures below another issues may arise:

- Searching for **romajs** (1st picture)
   - `Prossimi Event`/`Upcoming Events` section is not shown
   - `About RomaJS` language is mixed

- Searching for **roma js** everything is fine (2nd picture, both list of the pages and language).

1st
<img width="477" alt="image" src="https://github.com/user-attachments/assets/50f89daa-e69b-4e46-9228-d6fb3e6e1f12">

2nd
<img width="477" alt="image" src="https://github.com/user-attachments/assets/4d7e6e81-6dbf-4cac-9cef-62de040f6596">

**Comment by FaberVitale** [comment]
@giorgiogalassi thanks, appreciated:

I didn't know where to start 😅.

I'll look into that; structured data seems the likely solution

**Comment by FaberVitale** [comment]
Fixed 👍,

Thanks @giorgiogalassi 

<img width="811" alt="Screenshot 2024-10-22 at 18 46 28" src="https://github.com/user-attachments/assets/063898fd-44d7-49ac-99a2-44cde90646e2">
